### ISSUE TITLE
memory error training stories

### ISSUE THREAD

**Issue by smartinsightsfromdata** [RasaHQ/rasa-demo#281]
This is what happens. Please note I have 16GB RAM on Ubuntu 18.04 python 3.6
Any suggestion please?
```
$ make train-core
python3 -m rasa_core.train -d domain.yml -s data/core -c policy.yml --debug -o models/dialogue
/home/e/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
2019-02-15 14:25:50 DEBUG    rasa_core.training.generator  - Generated trackers will be deduplicated based on their unique last 6 states.
2019-02-15 14:25:50 DEBUG    rasa_core.training.generator  - Number of augmentation rounds is 3
2019-02-15 14:25:50 DEBUG    rasa_core.training.generator  - Starting data generation round 0 ... (with 1 trackers)
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████| 2112/2112 [00:03<00:00, 536.16it/s, # trackers=24]
2019-02-15 14:25:53 DEBUG    rasa_core.training.generator  - Finished phase (2843 training samples found).
2019-02-15 14:25:53 DEBUG    rasa_core.training.generator  - Data generation rounds finished.
2019-02-15 14:25:53 DEBUG    rasa_core.training.generator  - Found 0 unused checkpoints
2019-02-15 14:25:54 DEBUG    rasa_core.training.generator  - Starting augmentation round 0 ... (with 50 trackers)
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████| 2112/2112 [01:39<00:00,  6.67it/s, # trackers=288]
2019-02-15 14:27:33 DEBUG    rasa_core.training.generator  - Finished phase (67270 training samples found).
2019-02-15 14:27:33 DEBUG    rasa_core.training.generator  - Starting augmentation round 1 ... (with 50 trackers)
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████| 2112/2112 [02:19<00:00,  4.81it/s, # trackers=480]
2019-02-15 14:29:53 DEBUG    rasa_core.training.generator  - Finished phase (143027 training samples found).
2019-02-15 14:29:53 DEBUG    rasa_core.training.generator  - Starting augmentation round 2 ... (with 50 trackers)
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████| 2112/2112 [02:39<00:00,  3.98it/s, # trackers=500]
2019-02-15 14:32:33 DEBUG    rasa_core.training.generator  - Finished phase (218593 training samples found).
2019-02-15 14:32:33 DEBUG    rasa_core.training.generator  - Found 218593 training trackers.
2019-02-15 14:32:33 DEBUG    rasa_core.agent  - Agent trainer got kwargs: {}
2019-02-15 14:32:33 DEBUG    rasa_core.featurizers  - Creating states and action examples from collected trackers (by MaxHistoryTrackerFeaturizer(BinarySingleStateFeaturizer))...
Processed trackers: 100%|████████████████████████████████████████████████████████████████| 218593/218593 [06:56<00:00, 525.44it/s, # actions=340968]
2019-02-15 14:39:29 DEBUG    rasa_core.featurizers  - Created 340968 action examples.
Traceback (most recent call last):
  File "/home/e/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/e/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/e/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rasa_core/train.py", line 351, in <module>
    additional_args)
  File "/home/e/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rasa_core/train.py", line 266, in do_default_training
    kwargs=additional_arguments)
  File "/home/e/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rasa_core/train.py", line 190, in train_dialogue_model
    agent.train(training_data, **kwargs)
  File "/home/e/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rasa_core/agent.py", line 511, in train
    **kwargs)
  File "/home/e/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 60, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/home/e/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rasa_core/policies/keras_policy.py", line 143, in train
    shuffled_X, shuffled_y = training_data.shuffled_X_y()
  File "/home/e/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rasa_core/training/data.py", line 29, in shuffled_X_y
    shuffled_X = self.X[idx]
MemoryError
Makefile:22: recipe for target 'train-core' failed
make: *** [train-core] Error 1
```

**Comment by akelad** [comment]
Please add the `--augmentation 0` flag to the core training command
