### ISSUE TITLE
make train-core fail

### ISSUE THREAD

**Issue by zhs007** [RasaHQ/rasa-demo#310]
I am using the ``success`` branch

I train with docker, the script is

```
docker build -t rasa-demo .
mkdir models
docker run -v $PWD/models:/app/models rasa-demo make train-nlu
docker run -v $PWD/models:/app/models rasa-demo make train-core
```

Finally, train-core will report an error.

```
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

python3 -m rasa_core.train -d domain.yml -s data/new_fail/train_goal.md -c policy.yml --debug -o models/dialogue --augmentation 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/train.py", line 351, in <module>
    additional_args)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/train.py", line 266, in do_default_training
    kwargs=additional_arguments)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/train.py", line 172, in train_dialogue_model
    policies = config.load(policy_config)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/config.py", line 22, in load
    return PolicyEnsemble.from_dict(config_data)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 217, in from_dict
    policy_object = constr_func(**policy)
TypeError: 'NoneType' object is not callable

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Makefile:25: recipe for target 'train-core' failed
make: *** [train-core] Error 1
exit status 2
```

**Comment by akelad** [comment]
@zhs007 the `success` branch is in development, and not really designed to function properly. I'd suggest you use the master branch instead

**Comment by zhs007** [comment]
Thanks
