### ISSUE TITLE
bug in action server

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa-demo#422]
```
app_1              | Exception occurred while handling uri: 'http://app:5055/webhook'
app_1              | Traceback (most recent call last):
app_1              |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
app_1              |     response = await response
app_1              |   File "/app/rasa_sdk/endpoint.py", line 86, in webhook
app_1              |     result = await executor.run(action_call)
app_1              |   File "/app/rasa_sdk/executor.py", line 280, in run
app_1              |     events = action(dispatcher, tracker, domain)
app_1              |   File "/app/rasa_sdk/forms.py", line 532, in run
app_1              |     events.extend(self.submit(dispatcher, temp_tracker, domain))
app_1              |   File "/app/demo/actions.py", line 59, in submit
app_1              |     added_to_list = client.subscribe_user(config.mailchimp_list, email)
app_1              |   File "/app/demo/api.py", line 19, in subscribe_user
app_1              |     list_id, data={"email_address": email, "status": "pending"}
app_1              |   File "/usr/local/lib/python3.6/site-packages/mailchimp3/entities/listmembers.py", line 57, in create
app_1              |     check_email(data['email_address'])
app_1              |   File "/usr/local/lib/python3.6/site-packages/mailchimp3/helpers.py", line 62, in check_email
app_1              |     if not re.match(r".+@.+\..+", email):
app_1              |   File "/usr/local/lib/python3.6/re.py", line 172, in match
app_1              |     return _compile(pattern, flags).match(string)
app_1              | TypeError: expected string or bytes-like object
```

**Comment by erohmensing** [comment]
found this on the instance. Looks like somehow, whatever got passed to mailchimp as an email wasn't a string. Which seems super strange, but we should not validate non-strings, and probably do the regex compilation on our side as well (duckling should take care of that but can't be too safe)
