### ISSUE TITLE
Bugs in action server

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa-demo#463]
```
Attaching to rasa_app_1
app_1              | 2020-01-31 13:03:57 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_explain_sales_form'.
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_chitchat'.
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_faqs'.
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_pause'.
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_store_unknown_product'.
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_store_unknown_nlu_part'.
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_store_bot_language'.
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_store_entity_extractor'.
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_set_onboarding'.
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_store_problem_description'.
app_1              | 2020-01-31 13:03:58 INFO     rasa_sdk.executor  - Registered function for 'action_greet_user'.
app_1              | 2020-01-31 13:04:01 INFO     rasa_sdk.executor  - Registered function for 'action_default_ask_affirmation'.
app_1              | 2020-01-31 13:04:01 INFO     rasa_sdk.executor  - Registered function for 'action_default_fallback'.
app_1              | 2020-01-31 13:04:02 INFO     rasa_sdk.executor  - Registered function for 'action_get_community_events'.
app_1              | 2020-01-31 13:04:02 INFO     rasa_sdk.executor  - Registered function for 'action_next_step'.
app_1              | 2020-01-31 13:04:02 INFO     rasa_sdk.executor  - Registered function for 'action_docs_search'.
app_1              | 2020-01-31 13:04:02 INFO     rasa_sdk.executor  - Registered function for 'action_forum_search'.
app_1              | 2020-01-31 13:04:02 INFO     rasa_sdk.executor  - Registered function for 'subscribe_newsletter_form'.
app_1              | 2020-01-31 13:04:02 INFO     rasa_sdk.executor  - Registered function for 'sales_form'.
app_1              | 2020-01-31 13:04:02 INFO     rasa_sdk.executor  - Registered function for 'suggestion_form'.
app_1              | /app/rasa_sdk/executor.py:119: FutureWarning: Use of `utter_template` is deprecated. Use `utter_message(template=<template_name>)` instead.
app_1              |   FutureWarning,
app_1              | /app/rasa_sdk/executor.py:78: FutureWarning: Use of `utter_button_message` is deprecated. Use `utter_message(text=<text> , buttons=<list of buttons>)` instead.
app_1              |   FutureWarning,
app_1              | Exception occurred while handling uri: 'http://app:5055/webhook'
app_1              | Traceback (most recent call last):
app_1              |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
app_1              |     response = await response
app_1              |   File "/app/rasa_sdk/endpoint.py", line 86, in webhook
app_1              |     result = await executor.run(action_call)
app_1              |   File "/app/rasa_sdk/executor.py", line 280, in run
app_1              |     events = action(dispatcher, tracker, domain)
app_1              |   File "/app/demo/actions.py", line 723, in run
app_1              |     forum = discourse.get_discourse_links(doc_list.get("topics"), 0)
app_1              |   File "/app/demo/discourse.py", line 13, in get_discourse_links
app_1              |     doc_url = f"https://forum.rasa.com/t/{topics[index]['slug']}/{str(topics[index]['id'])}"
app_1              | TypeError: 'NoneType' object is not subscriptable
app_1              | 2020-01-31 13:39:12 ERROR    rasa_sdk.endpoint  - Failed to extract slot email with action subscribe_newsletter_form
app_1              | 2020-01-31 13:39:19 ERROR    rasa_sdk.endpoint  - Failed to extract slot email with action subscribe_newsletter_form
app_1              | Exception occurred while handling uri: 'http://app:5055/webhook'
app_1              | Traceback (most recent call last):
app_1              |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
app_1              |     response = await response
app_1              |   File "/app/rasa_sdk/endpoint.py", line 86, in webhook
app_1              |     result = await executor.run(action_call)
app_1              |   File "/app/rasa_sdk/executor.py", line 280, in run
app_1              |     events = action(dispatcher, tracker, domain)
app_1              |   File "/app/demo/actions.py", line 716, in run
app_1              |     search_text = last_user_event.get("text")
app_1              | AttributeError: 'NoneType' object has no attribute 'get'
app_1              | 2020-01-31 15:17:36 INFO     mailchimp3.client  - POST Request: https://us12.api.mailchimp.com/3.0/lists/297618692e/members
app_1              | 2020-01-31 15:17:36 INFO     mailchimp3.client  - PAYLOAD: {'email_address': 'a.buijk@rasa.com', 'status': 'pending'}
app_1              | 2020-01-31 15:17:36 INFO     mailchimp3.client  - POST Response: 400
app_1              | Exception occurred while handling uri: 'http://app:5055/webhook'
app_1              | Traceback (most recent call last):
app_1              |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
app_1              |     response = await response
app_1              |   File "/app/rasa_sdk/endpoint.py", line 86, in webhook
app_1              |     result = await executor.run(action_call)
app_1              |   File "/app/rasa_sdk/executor.py", line 280, in run
app_1              |     events = action(dispatcher, tracker, domain)
app_1              |   File "/app/demo/actions.py", line 716, in run
app_1              |     search_text = last_user_event.get("text")
app_1              | AttributeError: 'NoneType' object has no attribute 'get'
app_1              | 2020-02-01 17:56:23 ERROR    rasa_sdk.endpoint  - Failed to extract slot email with action subscribe_newsletter_form
app_1              | 2020-02-01 19:58:39 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-01 19:58:47 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-01 19:58:54 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-01 19:59:16 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | Exception occurred while handling uri: 'http://app:5055/webhook'
app_1              | Traceback (most recent call last):
app_1              |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
app_1              |     response = await response
app_1              |   File "/app/rasa_sdk/endpoint.py", line 86, in webhook
app_1              |     result = await executor.run(action_call)
app_1              |   File "/app/rasa_sdk/executor.py", line 280, in run
app_1              |     events = action(dispatcher, tracker, domain)
app_1              |   File "/app/demo/actions.py", line 724, in run
app_1              |     forum += "\n" + discourse.get_discourse_links(doc_list.get("topics"), 1)
app_1              |   File "/app/demo/discourse.py", line 13, in get_discourse_links
app_1              |     doc_url = f"https://forum.rasa.com/t/{topics[index]['slug']}/{str(topics[index]['id'])}"
app_1              | IndexError: list index out of range
app_1              | 2020-02-02 01:27:26 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | 2020-02-02 01:27:35 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | 2020-02-02 01:27:46 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | 2020-02-02 01:27:46 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | 2020-02-02 01:27:52 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | 2020-02-02 01:28:08 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | 2020-02-02 09:19:39 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:19:49 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:19:55 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:20:07 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:20:15 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:20:23 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:20:33 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:20:35 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:20:52 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:21:16 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:21:26 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:21:45 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:22:25 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:22:36 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:22:46 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:22:59 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:23:00 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 09:23:40 ERROR    rasa_sdk.endpoint  - Failed to extract slot person_name with action sales_form
app_1              | 2020-02-02 21:58:04 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-02 21:58:19 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-02 21:58:19 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | Exception occurred while handling uri: 'http://app:5055/webhook'
app_1              | Traceback (most recent call last):
app_1              |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
app_1              |     response = await response
app_1              |   File "/app/rasa_sdk/endpoint.py", line 86, in webhook
app_1              |     result = await executor.run(action_call)
app_1              |   File "/app/rasa_sdk/executor.py", line 280, in run
app_1              |     events = action(dispatcher, tracker, domain)
app_1              |   File "/app/demo/actions.py", line 723, in run
app_1              |     forum = discourse.get_discourse_links(doc_list.get("topics"), 0)
app_1              |   File "/app/demo/discourse.py", line 13, in get_discourse_links
app_1              |     doc_url = f"https://forum.rasa.com/t/{topics[index]['slug']}/{str(topics[index]['id'])}"
app_1              | TypeError: 'NoneType' object is not subscriptable
app_1              | 2020-02-03 06:04:59 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:05:07 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:05:12 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:05:20 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:05:26 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:05:36 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:05:50 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:05:55 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:06:11 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:06:11 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:06:35 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:06:41 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:06:46 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:06:46 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:06:50 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:06:57 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:07:04 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:07:14 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:07:20 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:07:25 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:07:40 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 06:07:51 ERROR    rasa_sdk.endpoint  - Failed to extract slot job_function with action sales_form
app_1              | 2020-02-03 07:48:44 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | 2020-02-03 07:48:56 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | 2020-02-03 07:49:07 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | 2020-02-03 07:49:14 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | Exception occurred while handling uri: 'http://app:5055/webhook'
app_1              | Traceback (most recent call last):
app_1              |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
app_1              |     response = await response
app_1              |   File "/app/rasa_sdk/endpoint.py", line 86, in webhook
app_1              |     result = await executor.run(action_call)
app_1              |   File "/app/rasa_sdk/executor.py", line 280, in run
app_1              |     events = action(dispatcher, tracker, domain)
app_1              |   File "/app/demo/actions.py", line 723, in run
app_1              |     forum = discourse.get_discourse_links(doc_list.get("topics"), 0)
app_1              |   File "/app/demo/discourse.py", line 13, in get_discourse_links
app_1              |     doc_url = f"https://forum.rasa.com/t/{topics[index]['slug']}/{str(topics[index]['id'])}"
app_1              | TypeError: 'NoneType' object is not subscriptable
app_1              | 2020-02-03 07:49:17 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | Exception occurred while handling uri: 'http://app:5055/webhook'
app_1              | Traceback (most recent call last):
app_1              |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
app_1              |     response = await response
app_1              |   File "/app/rasa_sdk/endpoint.py", line 86, in webhook
app_1              |     result = await executor.run(action_call)
app_1              |   File "/app/rasa_sdk/executor.py", line 280, in run
app_1              |     events = action(dispatcher, tracker, domain)
app_1              |   File "/app/demo/actions.py", line 723, in run
app_1              |     forum = discourse.get_discourse_links(doc_list.get("topics"), 0)
app_1              |   File "/app/demo/discourse.py", line 13, in get_discourse_links
app_1              |     doc_url = f"https://forum.rasa.com/t/{topics[index]['slug']}/{str(topics[index]['id'])}"
app_1              | TypeError: 'NoneType' object is not subscriptable
app_1              | 2020-02-03 07:49:38 ERROR    rasa_sdk.endpoint  - Failed to extract slot use_case with action sales_form
app_1              | Exception occurred while handling uri: 'http://app:5055/webhook'
app_1              | Traceback (most recent call last):
app_1              |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
app_1              |     response = await response
app_1              |   File "/app/rasa_sdk/endpoint.py", line 86, in webhook
app_1              |     result = await executor.run(action_call)
app_1              |   File "/app/rasa_sdk/executor.py", line 280, in run
app_1              |     events = action(dispatcher, tracker, domain)
app_1              |   File "/app/demo/actions.py", line 654, in run
app_1              |     step = int(tracker.get_slot("step")) + 1
app_1              | TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
I took a look in the logs of our action server on the deployment and there's a bunch of exceptions in there, we should fix them.

related: https://github.com/RasaHQ/rasa-demo/issues/422

**Comment by erohmensing** [comment]
I think this one https://github.com/RasaHQ/rasa-demo/issues/422 is related to the very last one: `int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by akelad** [comment]
@ArjaanBuijk would you have time to work on this relatively soon?

**Comment by ArjaanBuijk** [comment]
@akelad , I will look at this today.

**Comment by ArjaanBuijk** [comment]
**Log file snippet in description points to these bugs that need to be fixed:**

- [ ] demo/actions.py - class ActionDocsSearch(Action):
```
search_text = last_user_event.get("text")
AttributeError: 'NoneType' object has no attribute 'get'
```
---
- [ ] demo/discourse.py - get_discourse_links(--)
```
doc_url = f"https://forum.rasa.com/t/{topics[index]['slug']}/{str(topics[index]['id'])}"
TypeError: 'NoneType' object is not subscriptable
```
---
- [ ] demo/actions.py - class ActionNextStep(Action): 
```
step = int(tracker.get_slot("step")) + 1
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
---

**Comment by erohmensing** [comment]
Another one from my linked issue:
- [ ] demo/api.py - subscribe_user()
```
return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

**Comment by ArjaanBuijk** [comment]
@erohmensing ,
Are we using the `rasa-x-website-demo` or `killer-demo` VM instance ?
