### ISSUE TITLE
error occurs when rasa trian 

### ISSUE THREAD

**Issue by wj-Mcat** [RasaHQ/rasa-demo#553]
when I run the command: `rasa run actions --actions actions.actions`,  the error occurs:

```python
Exception occurred while handling uri: 'http://localhost:5055/'
Traceback (most recent call last):
  File "/Users/wujingwujing/miniconda3/envs/rasa/lib/python3.7/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/Users/wujingwujing/miniconda3/envs/rasa/lib/python3.7/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/Users/wujingwujing/miniconda3/envs/rasa/lib/python3.7/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
