### ISSUE TITLE
rasa demo - train issue

### ISSUE THREAD

**Issue by SreenijaK** [RasaHQ/rasa-demo#554]
rasa-version: 1.10.4
python-version: Python 3.6.9
os: ubuntu 18.04

I'm following this tutorial
https://blog.rasa.com/how-to-build-a-voice-assistant-with-open-source-rasa-and-mozilla-tools/

when i try  2.3 step : rasa train --augmentation 0

i get the following error.
Traceback (most recent call last):
  File "/home/sreenijak/python-envs/rasaenv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/sreenijak/python-envs/rasaenv/lib/python3.6/site-packages/rasa/__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/sreenijak/python-envs/rasaenv/lib/python3.6/site-packages/rasa/cli/train.py", line 76, in train
    additional_arguments=extract_additional_arguments(args),
  File "/home/sreenijak/python-envs/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/sreenijak/python-envs/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 101, in train_async
    additional_arguments,
  File "/home/sreenijak/python-envs/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 177, in _train_async_internal
    new_fingerprint, old_model, train_path
  File "/home/sreenijak/python-envs/rasaenv/lib/python3.6/site-packages/rasa/model.py", line 411, in should_retrain
    old_core, old_nlu = get_model_subdirectories(unpacked)
  File "/home/sreenijak/python-envs/rasaenv/lib/python3.6/site-packages/rasa/model.py", line 227, in get_model_subdirectories
    unpacked_model_path
rasa.exceptions.ModelNotFound: No NLU or Core data for unpacked model at: '/tmp/tmpka3syyaf'.

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by saykent** [comment]
Hi,
I'm getting same issue on macos with python 3.7.
`File "/Users/endi/Projects/Endi/Rasa/rasa-demo/venv3/lib/python3.7/site-packages/rasa/utils/tensorflow/model_data.py", line 107, in number_of_examples
    f"Number of examples differs for keys '{data.keys()}'. Number of "
ValueError: Number of examples differs for keys 'dict_keys(['text_features'])'. Number of examples should be the same for all data.`

**Comment by saykent** [comment]
Try 
`pip install rasa==1.9.7
rasa train`
It works for me.

The error is raised from def _create_model_data at diet_classifier.py

1.10.0
`for example in training_data:`

1.9.7
`        for e in training_data:
            if label_attribute is None or e.get(label_attribute):`
