### ISSUE TITLE
Downloading TF-Hub Module Not Found

### ISSUE THREAD

**Issue by mirfan899** [RasaHQ/rasa-demo#578]
I'm trying to setup the demo and this error shows up.
```shell
rasa train --augmentation 0
Training Core model...
Processed Story Blocks: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525/525 [00:00<00:00, 1173.31it/s, # trackers=1]
Processed trackers: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 439/439 [00:00<00:00, 508.83it/s, # actions=2067]
Epochs:   0%|                                                                                                                                                                                           | 0/20 [00:00<?, ?it/s]/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/utils/tensorflow/model_data.py:386: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  final_data[k].append(np.concatenate(np.array(v)))
Epochs: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:26<00:00,  1.31s/it, t_loss=1.146, loss=0.806, acc=0.993]
2020-10-03 14:03:58 INFO     rasa.utils.tensorflow.models  - Finished training.
Processed trackers: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 439/439 [00:00<00:00, 675.34it/s, # actions=1639]
Processed actions: 1639it [00:00, 17405.56it/s, # examples=1639]
Processed trackers: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 439/439 [00:00<00:00, 896.05it/s, # actions=939]
2020-10-03 14:03:59 INFO     rasa.core.agent  - Persisted model to '/tmp/tmpihb2qrjh/core'
Core model training completed.
Training NLU model...
2020-10-03 14:03:59 INFO     absl  - Using /tmp/tfhub_modules to cache modules.
2020-10-03 14:03:59 INFO     absl  - Downloading TF-Hub Module 'https://github.com/PolyAI-LDN/polyai-models/releases/download/v1.0/model.tar.gz'.
Traceback (most recent call last):
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/utils/train_utils.py", line 169, in load_tf_hub_model
    return tfhub.load(model_url)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/module_v2.py", line 97, in load
    module_path = resolve(handle)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/module_v2.py", line 53, in resolve
    return registry.resolver(handle)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/registry.py", line 42, in __call__
    return impl(*args, **kwargs)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 88, in __call__
    self._lock_file_timeout_sec())
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 415, in atomic_download
    download_fn(handle, tmp_dir)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 83, in download
    response = self._call_urlopen(request)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 96, in _call_urlopen
    return url.urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/cli/train.py", line 76, in train
    additional_arguments=extract_additional_arguments(args),
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/train.py", line 101, in train_async
    additional_arguments,
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/train.py", line 188, in _train_async_internal
    additional_arguments=additional_arguments,
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/train.py", line 245, in _do_training
    persist_nlu_training_data=persist_nlu_training_data,
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/train.py", line 482, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/nlu/train.py", line 75, in train
    trainer = Trainer(nlu_config, component_builder)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/nlu/model.py", line 145, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/nlu/model.py", line 157, in _build_pipeline
    component = component_builder.create_component(component_cfg, cfg)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/nlu/components.py", line 781, in create_component
    component = registry.create_component_by_config(component_config, cfg)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/nlu/registry.py", line 246, in create_component_by_config
    return component_class.create(component_config, config)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/nlu/components.py", line 489, in create
    return cls(component_config)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/nlu/tokenizers/convert_tokenizer.py", line 40, in __init__
    self.module = train_utils.load_tf_hub_model(self.model_url)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/rasa/utils/train_utils.py", line 173, in load_tf_hub_model
    return tfhub.load(model_url)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/module_v2.py", line 97, in load
    module_path = resolve(handle)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/module_v2.py", line 53, in resolve
    return registry.resolver(handle)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/registry.py", line 42, in __call__
    return impl(*args, **kwargs)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 88, in __call__
    self._lock_file_timeout_sec())
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 415, in atomic_download
    download_fn(handle, tmp_dir)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 83, in download
    response = self._call_urlopen(request)
  File "/home/irfan/PycharmProjects/rasa-demo/.rasa_voice/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 96, in _call_urlopen
    return url.urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

https://github.com/PolyAI-LDN/polyai-models not available as they have updated the doc with the information. Now how to move forward from this point?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JustinaPetr** [comment]
Hi @mirfan899. This is a known issue, we are working on making the necessary changes. As a short term solution, you should be able to go around this issue by updating the `config.yml` file and removing the components:

```
- name: ConveRTTokenizer
- name: ConveRTFeaturizer
```

**Comment by mirfan899** [comment]
I'm getting this error after removing the lines.
```shell
rasa.nlu.config.InvalidConfigError: 'RegexFeaturizer' requires ['Tokenizer']. Add required components to the pipeline.
```

When I use `WhitespaceTokenizer` before `RegexFeaturizer`, it works otherwise it throws above error!!!

**Comment by JustinaPetr** [comment]
@mirfan899 Yes, that's a very good point. You should include the `WhitespaceTokenizer` as otherwise there will be no tokenizer in the pipeline and the featurizer will fail to extract the features. 

If it works with the pipeline updates I will close this one. As I have mentioned, we are working on finding a permanent solution for this issue and will share the updates as soon as possible.

**Comment by mlacayoemery** [comment]
See https://github.com/RasaHQ/rasa/issues/6806 for a solution

1. Update Rasa to version 1.10.14 so you get model_url flag support for the configuration file
2. Modify the top of file rasa-demo\config.yml

From:

```
language: en
pipeline:
- name: ConveRTTokenizer
- name: ConveRTFeaturizer
- name: RegexFeaturizer
```

To:

```
language: en
pipeline:
- name: ConveRTTokenizer
  model_url: https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
- name: ConveRTFeaturizer
  model_url: https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
- name: RegexFeaturizer
```

3. Retrain your models

That's it

**Comment by mlacayoemery** [comment]
See https://github.com/RasaHQ/rasa/issues/6806 for a solution

1. Update Rasa to version 1.10.14 so you get model_url flag support for the configuration file
2. Modify the top of file rasa-demo\config.yml

From:

```
language: en
pipeline:
- name: ConveRTTokenizer
- name: ConveRTFeaturizer
- name: RegexFeaturizer
```

To:

```
language: en
pipeline:
- name: ConveRTTokenizer
  model_url: https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
- name: ConveRTFeaturizer
  model_url: https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
- name: RegexFeaturizer
```

3. Retrain your models

That's it

**Comment by X-MOD-I** [comment]
> See [RasaHQ/rasa#6806](https://github.com/RasaHQ/rasa/issues/6806) for a solution
> 
> 1. Update Rasa to version 1.10.14 so you get model_url flag support for the configuration file
> 2. Modify the top of file rasa-demo\config.yml
> 
> From:
> 
> ```
> language: en
> pipeline:
> - name: ConveRTTokenizer
> - name: ConveRTFeaturizer
> - name: RegexFeaturizer
> ```
> 
> To:
> 
> ```
> language: en
> pipeline:
> - name: ConveRTTokenizer
>   model_url: https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
> - name: ConveRTFeaturizer
>   model_url: https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
> - name: RegexFeaturizer
> ```
> 
> 1. Retrain your models
> 
> That's it

Thanks ,It worked for me
