### ISSUE TITLE
ModuleNotFoundError: No module named 'demo.actions'

### ISSUE THREAD

**Issue by MichaelMano3** [RasaHQ/rasa-demo#592]
Hi ,when i run rasa run actions --actions demo.actions,i got this error and don't know the reason,can anyone help me  solve this.

here is the log:

2020-10-26 01:07:37 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2020-10-26 01:07:37 ERROR    rasa_sdk.executor  - Failed to register package 'demo.actions'.
Traceback (most recent call last):
  File "/home/yang/.local/lib/python3.6/site-packages/rasa_sdk/executor.py", line 250, in register_package
    self._import_submodules(package)
  File "/home/yang/.local/lib/python3.6/site-packages/rasa_sdk/executor.py", line 206, in _import_submodules
    package = self._import_module(package)
  File "/home/yang/.local/lib/python3.6/site-packages/rasa_sdk/executor.py", line 227, in _import_module
    module = importlib.import_module(name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'demo.actions'

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
@MichaelMano3 Does `rasa run actions` work?

**Comment by MichaelMano3** [comment]
> @MichaelMano3 Does `rasa run actions` work?

Yes ,rasa run actions work.and also pip install -e . shows rasa-demo install successful.

rasa run actions
2020-10-26 20:16:51 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_explain_sales_form'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_explain_faq'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_set_faq_slot'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_pause'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_store_unknown_product'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_store_unknown_nlu_part'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_store_bot_language'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_store_entity_extractor'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_set_onboarding'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_store_problem_description'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_greet_user'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_default_ask_affirmation'.
2020-10-26 20:17:04 INFO     rasa_sdk.executor  - Registered function for 'action_default_fallback'.
2020-10-26 20:17:06 WARNING  actions.api.community_events  - Error when trying to parse event details from html.
'NavigableString' object has no attribute 'get'
2020-10-26 20:17:06 WARNING  actions.api.community_events  - Error when trying to parse event details from html.
'NavigableString' object has no attribute 'get'
2020-10-26 20:17:06 WARNING  actions.api.community_events  - Error when trying to parse event details from html.
'NavigableString' object has no attribute 'get'
2020-10-26 20:17:06 WARNING  actions.api.community_events  - Error when trying to parse event details from html.
'NavigableString' object has no attribute 'get'
2020-10-26 20:17:06 INFO     rasa_sdk.executor  - Registered function for 'action_get_community_events'.
2020-10-26 20:17:06 INFO     rasa_sdk.executor  - Registered function for 'action_next_step'.
2020-10-26 20:17:06 INFO     rasa_sdk.executor  - Registered function for 'action_docs_search'.
2020-10-26 20:17:06 INFO     rasa_sdk.executor  - Registered function for 'action_forum_search'.
2020-10-26 20:17:06 INFO     rasa_sdk.executor  - Registered function for 'action_tag_feedback'.
2020-10-26 20:17:06 INFO     rasa_sdk.executor  - Registered function for 'action_tag_docs_search'.
2020-10-26 20:17:06 INFO     rasa_sdk.executor  - Registered function for 'subscribe_newsletter_form'.
2020-10-26 20:17:06 INFO     rasa_sdk.executor  - Registered function for 'sales_form'.
2020-10-26 20:17:06 INFO     rasa_sdk.executor  - Registered function for 'suggestion_form'.
2020-10-26 20:17:06 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://localhost:5055

**Comment by TyDunn** [comment]
@MichaelMano3 So why are trying to use the `rasa run actions --actions demo.actions` command?

**Comment by MichaelMano3** [comment]
> @MichaelMano3 So why are trying to use the `rasa run actions --actions demo.actions` command?
I'm following this tutor to creat the voice assistant, it need `rasa run actions --actions demo.actions` command.i try to use 'rasa run actions --actions actions.actions' command but it seems  dont work with this tutor.
https://medium.com/rasa-blog/how-to-build-a-voice-assistant-with-open-source-rasa-and-mozilla-tools-c05c4ec698c6

**Comment by TyDunn** [comment]
@MichaelMano3 This is a rather old blog post. You just need to use `rasa run actions` instead
