### ISSUE TITLE
Failed to register package actions.actions.

### ISSUE THREAD

**Issue by programmeddeath1** [RasaHQ/rasa-demo#601]
Traceback (most recent call last):
  File "/home/abhilash/.local/lib/python3.6/site-packages/rasa_sdk/executor.py", line 254, in register_package
    self._import_submodules(package)
  File "/home/abhilash/.local/lib/python3.6/site-packages/rasa_sdk/executor.py", line 210, in _import_submodules
    package = self._import_module(package)
  File "/home/abhilash/.local/lib/python3.6/site-packages/rasa_sdk/executor.py", line 231, in _import_module
    module = importlib.import_module(name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/abhilash/Projects/chatbots/rasa-demo/actions/actions.py", line 21, in <module>
    from actions.api.algolia import AlgoliaAPI
  File "/home/abhilash/Projects/chatbots/rasa-demo/actions/api/algolia.py", line 7, in <module>
    en_spacy = spacy.load("en")
  File "/home/abhilash/.local/lib/python3.6/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/home/abhilash/.local/lib/python3.6/site-packages/spacy/util.py", line 164, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/abhilash/.local/lib/python3.6/site-packages/spacy/util.py", line 184, in load_model_from_package
    cls = importlib.import_module(name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'en'

I am getting this error on running run actions. On first look it seems like an error with spacy loading en module. I have installed the spacy module but the error seems to persist.
Any help would be appreciated.

**Comment by sara-tagger** [comment]
Thanks for the issue, @alopez will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by samsucik** [comment]
Hey @programmeddeath1, have a look at #580. In short, you'll need to install an English Spacy model:
```bash
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en
```
However, bear in mind that some bits of the Sara bot won't run locally as they require special API keys (such as the docs search in `action_docs_search` that follows after the `technical_question` intent).

**Comment by aanchan** [comment]
Hello, I ran into another curious problem where it says 

> DeprecationWarning: The command link is deprecated.
> ⚠ As of spaCy v3.0, model symlinks are deprecated. You can load trained
> pipeline packages using their full names or from a directory path.
>
