### ISSUE TITLE
Training fails on windows 10 , python 3.6

### ISSUE THREAD

**Issue by geekDecker** [RasaHQ/rasa-demo#604]
I was trying to train rasa on windows 10 , python 3.6 with rasa 2.0.8 training stops after starting DIET Classifier
 Please help me resolve issue . I am stuck since two days 

here are the logs .
2021-01-08 19:59:04 INFO     rasa.nlu.model  - Starting to train component DIETClassifier
Traceback (most recent call last):
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\KNI9KOR\Anaconda3\envs\rasabot\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\cli\train.py", line 90, in train
    nlu_additional_arguments=extract_nlu_additional_arguments(args),
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\train.py", line 55, in train
    loop,
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\utils\common.py", line 308, in run_in_loop
    result = loop.run_until_complete(f)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\asyncio\base_events.py", line 488, in run_until_complete
    return future.result()
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\train.py", line 110, in train_async
    nlu_additional_arguments=nlu_additional_arguments,
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\train.py", line 207, in _train_async_internal
    old_model_zip_path=old_model,
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\train.py", line 246, in _do_training
    additional_arguments=nlu_additional_arguments,
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\train.py", line 547, in _train_nlu_with_validated_data
    **additional_arguments,
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\nlu\train.py", line 114, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\nlu\model.py", line 206, in train
    updates = component.train(working_data, self.config, **context)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\nlu\classifiers\diet_classifier.py", line 760, in train
    self.model = self._instantiate_model_class(model_data)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\nlu\classifiers\diet_classifier.py", line 1086, in _instantiate_model_class
    config=self.component_config,
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\nlu\classifiers\diet_classifier.py", line 1104, in __init__
    super().__init__("DIET", config, data_signature, label_data)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\utils\tensorflow\models.py", line 654, in __init__
    checkpoint_model=config[CHECKPOINT_MODEL],
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\rasa\utils\tensorflow\models.py", line 83, in __init__
    super().__init__(**kwargs)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\keras\engine\training.py", line 308, in __init__
    self._init_batch_counters()
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\keras\engine\training.py", line 317, in _init_batch_counters
    self._train_counter = variables.Variable(0, dtype='int64', aggregation=agg)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\ops\variables.py", line 262, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\ops\variables.py", line 256, in _variable_v2_call
    shape=shape)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\ops\variables.py", line 237, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2646, in default_variable_creator_v2
    shape=shape)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1518, in __init__
    distribute_strategy=distribute_strategy)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1666, in _init_from_args
    graph_mode=self._in_graph_mode)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 243, in eager_safe_variable_handle
    shape, dtype, shared_name, name, graph_mode, initial_value)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 175, in _variable_handle_from_shape_and_dtype
    math_ops.logical_not(exists), [exists], name="EagerVariableNameReuse")
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 49, in _assert
    _ops.raise_from_not_ok_status(e, name)
  File "c:\users\kni9kor\anaconda3\envs\rasabot\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
